Add version information and cmake install configuration
Godlike/Arion pull request #12
Opened 2018-02-14 00:34 UTC by dsodintsov

2018-02-15 13:30 UTC, ilia-glushchenko approved these changes

2018-02-15 13:32 UTC, ilia-glushchenko requested changes

2018-02-15 13:32 UTC, ilia-glushchenko commented on Arion/ArionVersionInfo.rc.in
> +#include <Windows.h>
Copyrights?

2018-02-17 20:17 UTC, dsodintsov commented on Arion/ArionVersionInfo.rc.in
> +#include <Windows.h>
Done

2018-02-17 21:37 UTC, ilia-glushchenko commented
Please open the issue and add its index to the commit message.

2018-02-17 23:00 UTC, dsodintsov commented
Done

2018-02-17 23:02 UTC, ilia-glushchenko approved these changes

2018-02-18 17:32 UTC, krupitskas approved these changes

2018-02-18 17:33 UTC, merged