[#17] EPA blow up polytope handling simplex of size 1
Godlike/Arion pull request #18
Opened 2018-03-24 21:04 UTC by ilia-glushchenko

2018-03-25 01:27 UTC, MrDmitry requested changes

2018-03-25 01:27 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersection.hpp
> + * @attention Must be called strictly after the corresponding CalculateIntersection function call, otherwise result is undefined
right now both `CalculateContactNormal` and `CalculateContactManifold` have to be called `strictly after the corresponding CalculateIntersection function call`
does `strictly` apply?

2018-03-25 01:27 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersection.hpp
> +inline ContactPoints  CalculateContactPoints<Box, Plane>(SimpleShape const* a, SimpleShape const* b, CacheBase* cacheBase)
double space `ContactPoints  CalculateContactPoints`

2018-03-25 01:27 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersectionDetector.hpp
> +    * @attention Must be called strictly after the corresponding CalculateIntersection function call, otherwise result is undefined
same question as before - strictness conflict with `CalculateContactNormal`

2018-03-25 15:11 UTC, MrDmitry approved these changes

2018-03-25 17:01 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersection.hpp
> +    auto const box = static_cast<Box const*>(b);
should the `plane` be `const` as well?

2018-03-25 17:07 UTC, ilia-glushchenko commented on Arion/include/Arion/SimpleShapeIntersection.hpp
> +    auto const box = static_cast<Box const*>(b);
it should

2018-03-25 18:40 UTC, MrDmitry approved these changes

2018-03-28 08:29 UTC, t0mgit commented
nice.

2018-03-28 08:29 UTC, t0mgit commented
approve

2018-03-28 08:29 UTC, merged