[#19] SSI and SSID contact normal calculation from first body perspective
Godlike/Arion pull request #20
Opened 2018-03-28 08:33 UTC by ilia-glushchenko

2018-03-29 14:10 UTC, MrDmitry requested changes

2018-03-29 14:10 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersectionDetector.hpp
> +     * @brief Calculates surface contact normal of a shape
`of shape @p a`?

2018-03-29 14:10 UTC, dsodintsov commented on Arion/include/Arion/SimpleShapeIntersection.hpp
> + * @brief Calculates surface contact normal of a shape using shapes and cache data and returns it
`of shape @p a`?

2018-04-25 13:15 UTC, MrDmitry approved these changes

2018-04-25 13:40 UTC, krupitskas approved these changes

2018-04-25 14:06 UTC, merged