[#23] Improve SSID performance
Godlike/Arion pull request #24
Opened 2018-07-05 19:06 UTC by ilia-glushchenko

2018-07-05 19:19 UTC, MrDmitry requested changes

2018-07-05 19:19 UTC, dsodintsov commented on Arion/include/Arion/ConfigurationSpaceObject.hpp
> +    return LazySupport(sphere, direction);;
double semicolon

2018-07-05 19:19 UTC, dsodintsov commented on Arion/include/Arion/ConfigurationSpaceObject.hpp
> +    return LazySupport(sphere, direction);;
Could you try aliasing with `using` instead?

2018-07-05 22:29 UTC, MrDmitry approved these changes

2018-07-09 11:14 UTC, krupitskas approved these changes

2018-07-09 11:14 UTC, merged